### ISSUE TITLE
Duplicate Root CA Certificates

### ISSUE THREAD

**Issue by GD-Dal** [trippsc2/ansible-collection-adcs#1]
Hi. I got my friend Github Copilot to write a much better description of the problem that I can:

# Certificate Duplication Issue in certificate_authority Role

## Summary
The `trippsc2.adcs.certificate_authority` role systematically creates duplicate root CA certificates in the Windows certificate store (`Cert:\LocalMachine\Root`) during CA installation. This occurs consistently across different domains and fresh installations.

## Environment
- **OS**: Windows Server 2022 Standard
- **Ansible Collection**: `trippsc2.adcs`
- **Role**: `certificate_authority`
- **PowerShell Modules**: ActiveDirectoryCSDsc (pre-installed via offline template)
- **Domain Environment**: Active Directory integrated

## Issue Description
After running the `certificate_authority` role, **two identical certificates** with the same thumbprint, serial number, and dates are created in the Trusted Root Certificate Authorities store. This duplication is reproducible and systematic.

## Reproduction Steps
1. Deploy Windows Server 2022 in AD domain
2. Run the `certificate_authority` role with these parameters:
   ```yaml
   - role: trippsc2.adcs.certificate_authority
     vars:
       winca_ca_cert_common_name: "{{ location }}-Valg Enterprise Root CA v2"
       winca_username: "{{ ansible_user }}"
       winca_password: "{{ ansible_password }}"
       winca_is_ad_integrated: true
       winca_is_root_ca: true
       winca_overwrite_existing_ca_in_domain: true
       winca_overwrite_existing_database: true
       winca_overwrite_existing_key: true
       winca_crypto_provider_name: "Microsoft Software Key Storage Provider"
       winca_crypto_provider_algorithm: "rsa"
       winca_key_length: 2048
       winca_hash_algorithm_name: "sha256"
       winca_ca_cert_validity_period: 10
       winca_ca_cert_validity_period_unit: "Years"
   ```
3. Check certificate store: `Get-ChildItem -Path 'Cert:\LocalMachine\Root' | Where-Object Subject -like '*YourCA*'`

## Expected Behavior
One root CA certificate should be created in the Trusted Root store.

## Actual Behavior
Two identical certificates are created with:
- Same thumbprint
- Same serial number  
- Same subject
- Same validity dates

### Domain 1 (AK):
```
Subject      : CN=AK-Valg Enterprise Root CA v2, DC=akvalg, DC=lan
Thumbprint   : 54F88A4E9459F9E2CFD81C0BBFF555D871907E3C
SerialNumber : 7A997D8A0279E7964260BB92C4F19E33
NotBefore    : 26.06.2025 15:00:52
NotAfter     : 26.06.2035 15:10:51

Subject      : CN=AK-Valg Enterprise Root CA v2, DC=akvalg, DC=lan
Thumbprint   : 54F88A4E9459F9E2CFD81C0BBFF555D871907E3C
SerialNumber : 7A997D8A0279E7964260BB92C4F19E33
NotBefore    : 26.06.2025 15:00:52
NotAfter     : 26.06.2035 15:10:51
```

### Domain 2 (HK):
```
Subject      : CN=HK-Valg Enterprise Root CA v2, DC=hkvalg, DC=lan
Thumbprint   : 89E9DD9187A45C3371F0BD5149974CF11E01FB18
SerialNumber : 306FA75BEBA91A8F4F3A2C27704AC515
NotBefore    : 26.06.2025 15:33:21
NotAfter     : 26.06.2035 15:43:20

Subject      : CN=HK-Valg Enterprise Root CA v2, DC=hkvalg, DC=lan
Thumbprint   : 89E9DD9187A45C3371F0BD5149974CF11E01FB18
SerialNumber : 306FA75BEBA91A8F4F3A2C27704AC515
NotBefore    : 26.06.2025 15:33:21
NotAfter     : 26.06.2035 15:43:20
```

## Testing Performed
- ✅ Tested across multiple domains (AK, HK)
- ✅ Tested on fresh installations 
- ✅ Tested with `winca_overwrite_*` parameters set to `true`
- ✅ Tested with clean certificate stores before installation
- ✅ Issue reproduces consistently

## Impact
- **Functional**: None - CA works correctly
- **Cosmetic**: Certificate store shows confusing duplicates
- **Management**: Complicates certificate inventory and troubleshooting

## Workaround
We've created a cleanup script that removes duplicates by thumbprint:
```powershell
$certs = Get-ChildItem -Path 'Cert:\LocalMachine\Root' | Where-Object Subject -like '*YourCA*'
$groups = $certs | Group-Object Thumbprint
foreach ($group in $groups) {
    if ($group.Count -gt 1) {
        for ($i = 1; $i -lt $group.Count; $i++) {
            Remove-Item -Path "Cert:\LocalMachine\Root\$($group.Group[$i].Thumbprint)" -Force
        }
    }
}
```

## Questions
1. Is this a known issue with the ActiveDirectoryCSDsc module?
2. Could this be related to how certificates are installed during CA configuration?
3. Are there any role parameters that could prevent this duplication?

## Additional Information
- Role completes successfully without errors
- CA functionality is not affected
- Issue occurs regardless of certificate name or domain
- Clean installations exhibit the same behavior

Thank you for this excellent collection! The certificate authority role works great functionally - this duplication appears to be just a certificate store management quirk.
